include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
  - project: devops/gitlab-ci
    file: chef/cookbook.gitlab-ci.yml

verify:
  parallel:
    matrix:
      - SUITE: default
        PLATFORM:
          - debian-10
          - debian-11
          - debian-12
        CHEF_VERSION: 18
